# GLM intro



## GLM case study: Are Emily and Greg More Employable Than Lakisha and Jamal?


paper link: https://www.povertyactionlab.org/sites/default/files/research-paper/3%20A%20Field%20Experiment%20on%20Labor%20Market%20Discrimination%20Sep%2004.pdf

Data from: https://www.openicpsr.org/openicpsr/project/116023/version/V1/view?path=/openicpsr/116023/fcr:versions/V1/lakisha_aer.dta&type=file

data from: 


The table below details all of the data set available from https://www.openintro.org/data/index.php?data=lakisha. 

| Variable | Description |
| :--- | :--- |
| `education` | Highest education (0=not reported; 1=high school diploma; 2=high school graduate; 3=some college; 4=college or more) |
| `n_jobs` | Number of jobs listed on resume |
| `years_exp` | Number of years of work experience on the resume |
| `honors` | Indicator: 1 if resume mentions honors |
| `volunteer` | Indicator: 1 if resume mentions volunteering experience |
| `military` | Indicator: 1 if resume mentions military experience |
| `emp_holes` | Indicator: 1 if resume mentions employment holes |
| `occup_specific` | 1990 Census Occupation Code |
| `occup_broad` | Broad occupation (1=executives/managerial; 2=admin supervisors; 3=sales reps; 4=sales workers; 5=secretaries/legal; 6=clerical) |
| `work_in_school` | Indicator: 1 if resume mentions work experience while at school |
| `email` | Indicator: 1 if email address is on the resume |
| `computer_skills` | Indicator: 1 if resume mentions computer skills |
| `special_skills` | Indicator: 1 if resume mentions special skills |
| `first_name` | Applicant's first name |
| `sex` | Sex ('f' = female; 'm' = male) |
| `race` | Race ('b' = black; 'w' = white) |
| `h` | Indicator: 1 = high quality resume |
| `l` | Indicator: 1 = low quality resume |
| `call` | Indicator: 1 = applicant was called back |
| `city` | City ('c' = Chicago; 'b' = Boston) |
| `kind` | Job kind ('a' = administrative; 's' = sales) |
| `ad_id` | Employment ad identifier |
| `frac_black` | Fraction of blacks in applicant's zip |
| `frac_white` | Fraction of whites in applicant's zip |
| `l_med_hh_inc` | Log median household income in applicant's zip |
| `frac_dropout` | Fraction of high-school dropouts in applicant's zip |
| `frac_colp` | Fraction of college degree or more in applicant's zip |
| `l_inc` | Log per capita income in applicant's zip |
| `col` | Indicator: 1 = applicant has college degree or more |
| `expminreq` | Minimum experience required (in years) |
| `school_req` | Specific education requirement ('hsg', 'somcol', 'colp') |
| `eoe` | Indicator: 1 if ad mentions 'Equal Opportunity Employer' |
| `parent_sales` | Sales of parent company (millions USD) |
| `parent_emp` | Number of parent company employees |
| `branch_sales` | Sales of branch (millions USD) |
| `branch_emp` | Number of branch employees |
| `fed` | Indicator: 1 if employer is a federal contractor |
| `frac_black_emp_zip` | Fraction of blacks in employer's zipcode |
| `frac_white_emp_zip` | Fraction of whites in employer's zipcode |
| `l_med_hh_inc_emp_zip` | Log median household income in employer's zipcode |
| `frac_dropout_emp_zip` | Fraction of high-school dropouts in employer's zipcode |
| `frac_colp_emp_zip` | Fraction of college degree or more in employer's zipcode |
| `l_inc_emp_zip` | Log per capita income in employer's zipcode |
| `manager` | Indicator: 1 if executives/managers wanted |
| `supervisor` | Indicator: 1 if administrative supervisors wanted |
| `secretary` | Indicator: 1 if secretaries/legal assistants wanted |
| `off_support` | Indicator: 1 if clerical workers wanted |
| `sales_rep` | Indicator: 1 if sales representative wanted |
| `retail_sales` | Indicator: 1 if retail sales worker wanted |
| `req` | Indicator: 1 if ad mentions any requirement |
| `exp_req` | Indicator: 1 if ad mentions experience requirement |
| `com_req` | Indicator: 1 if ad mentions communication skills requirement |
| `educ_req` | Indicator: 1 if ad mentions educational requirement |
| `comp_req` | Indicator: 1 if ad mentions computer skill requirement |
| `org_req` | Indicator: 1 if ad mentions organizational skills requirement |
| `manuf` | Indicator: 1 if industry is manufacturing |
| `trans_com` | Indicator: 1 if industry is transport/communication |
| `bank_real` | Indicator: 1 if industry is finance/insurance/real estate |
| `trade` | Indicator: 1 if industry is wholesale/retail trade |
| `bus_service` | Indicator: 1 if industry is business/personal services |
| `oth_service` | Indicator: 1 if industry is health/education/social services |
| `miss_ind` | Indicator: 1 if industry is other/unknown |
| `ownership` | Ownership status ('non-profit'; 'private'; 'public') |

In [352]:
%reset -f

In [353]:
import numpy             as np
import statsmodels.api   as sm
import pandas            as pd
import seaborn           as sns

from statsmodels.discrete.discrete_model import LogitResults

from statsmodels.iolib.summary2 import summary_col

In [354]:
df = pd.read_stata("/home/michael/Projects/regression_analysis/data/lakisha_aer.dta")
#df = pd.read_csv("/home/michael/Projects/regression_analysis/data/lakisha.csv")

In [355]:
df.columns

Index(['id', 'ad', 'education', 'ofjobs', 'yearsexp', 'honors', 'volunteer',
       'military', 'empholes', 'occupspecific', 'occupbroad', 'workinschool',
       'email', 'computerskills', 'specialskills', 'firstname', 'sex', 'race',
       'h', 'l', 'call', 'city', 'kind', 'adid', 'fracblack', 'fracwhite',
       'lmedhhinc', 'fracdropout', 'fraccolp', 'linc', 'col', 'expminreq',
       'schoolreq', 'eoe', 'parent_sales', 'parent_emp', 'branch_sales',
       'branch_emp', 'fed', 'fracblack_empzip', 'fracwhite_empzip',
       'lmedhhinc_empzip', 'fracdropout_empzip', 'fraccolp_empzip',
       'linc_empzip', 'manager', 'supervisor', 'secretary', 'offsupport',
       'salesrep', 'retailsales', 'req', 'expreq', 'comreq', 'educreq',
       'compreq', 'orgreq', 'manuf', 'transcom', 'bankreal', 'trade',
       'busservice', 'othservice', 'missind', 'ownership'],
      dtype='object')

In [356]:
df = sm.add_constant(df)
df['years_exp_sq'] = df['yearsexp'] ** 2
df['city_dummy'] = np.where(df["city"] == "c",1,0)
df['white_dummy'] = np.where(df['race']=="w", 1,0)
df['sex_dummy'] = np.where(df["sex"] == "m",1,0)
df["hl_dummy"] = np.where(df['h'] == 1, "high", "low")
df.columns

Index(['const', 'id', 'ad', 'education', 'ofjobs', 'yearsexp', 'honors',
       'volunteer', 'military', 'empholes', 'occupspecific', 'occupbroad',
       'workinschool', 'email', 'computerskills', 'specialskills', 'firstname',
       'sex', 'race', 'h', 'l', 'call', 'city', 'kind', 'adid', 'fracblack',
       'fracwhite', 'lmedhhinc', 'fracdropout', 'fraccolp', 'linc', 'col',
       'expminreq', 'schoolreq', 'eoe', 'parent_sales', 'parent_emp',
       'branch_sales', 'branch_emp', 'fed', 'fracblack_empzip',
       'fracwhite_empzip', 'lmedhhinc_empzip', 'fracdropout_empzip',
       'fraccolp_empzip', 'linc_empzip', 'manager', 'supervisor', 'secretary',
       'offsupport', 'salesrep', 'retailsales', 'req', 'expreq', 'comreq',
       'educreq', 'compreq', 'orgreq', 'manuf', 'transcom', 'bankreal',
       'trade', 'busservice', 'othservice', 'missind', 'ownership',
       'years_exp_sq', 'city_dummy', 'white_dummy', 'sex_dummy', 'hl_dummy'],
      dtype='object')

In [357]:
df['req'].std()

0.4092753529548645

In [358]:
# Set up lists to filter data in modelling stage
X = ['const', 
     #'white_dummy',
     # variables from table 5
     'yearsexp', 
     #'years_exp_sq',
     'honors',
     'volunteer',
     'military', 
     'email',
     'empholes',
     'workinschool', 
     'computerskills', 
     'specialskills',
     # a city dummy
     'city_dummy',
     # a sex dummy
     'sex_dummy',   
     #  six occupation dummies
     'manager', 
     'supervisor', 
     'secretary', 
     'offsupport',
     'salesrep', 
     'retailsales',
     # a vector of dummy variables for job requirements as listed in the employment ad 
     # (see Section III, subsection D, for details).
     'expreq', 
     'comreq',
     'educreq',
     'compreq',
     'orgreq'
    ]


y = "call" # dependent variable is the callback dumm
# set up objects to filter for African-American and white names
T = 'race'

In [359]:
df.groupby(T)[y].describe()

       count      mean       std  min  25%  50%  75%  max
race
b     2435.0  0.064476  0.245649  0.0  0.0  0.0  0.0  1.0
w     2435.0  0.096509  0.295346  0.0  0.0  0.0  0.0  1.0

In [360]:
df.groupby([T,"hl_dummy"])[y].mean().reset_index()

  race hl_dummy      call
0    b     high  0.067048
1    b      low  0.061881
2    w     high  0.107931
3    w      low  0.084983

In [361]:
df.groupby(T)[X].mean().T

race                   b         w
const           1.000000  1.000000
yearsexp        7.829569  7.856263
honors          0.051335  0.054209
volunteer       0.414374  0.408624
military        0.101848  0.092402
email           0.479671  0.478850
empholes        0.445996  0.450103
workinschool    0.560986  0.558111
computerskills  0.832444  0.808624
specialskills   0.327310  0.330185
city_dummy      0.555236  0.555236
sex_dummy       0.225462  0.236140
manager         0.151951  0.152361
supervisor      0.077207  0.077207
secretary       0.333060  0.332649
offsupport      0.118686  0.118686
salesrep        0.151129  0.151129
retailsales     0.167967  0.167967
expreq          0.435318  0.435318
comreq          0.124846  0.124846
educreq         0.106776  0.106776
compreq         0.437372  0.436961
orgreq          0.072690  0.072690

In [362]:
df.groupby("hl_dummy")[X].mean().T

hl_dummy            high       low
const           1.000000  1.000000
yearsexp        8.294358  7.387376
honors          0.071137  0.034241
volunteer       0.792314  0.027228
military        0.190106  0.003300
email           0.923957  0.030528
empholes        0.339738  0.557343
workinschool    0.718316  0.399340
computerskills  0.909648  0.730611
specialskills   0.357727  0.299505
city_dummy      0.557645  0.552805
sex_dummy       0.231807  0.229785
manager         0.153720  0.150578
supervisor      0.083401  0.070957
secretary       0.331971  0.333746
offsupport      0.118561  0.118812
salesrep        0.149632  0.152640
retailsales     0.162715  0.173267
expreq          0.439493  0.431106
comreq          0.123467  0.126238
educreq         0.108749  0.104785
compreq         0.441128  0.433168
orgreq          0.074407  0.070957

# Probit coefficients and Marginal effect table

In [363]:
probit_res = sm.Probit(df[y], 
                       df[["white_dummy", "h"] + X]).fit(cov_type='cluster',
                                                         cov_kwds={'groups': df['adid']})

print(probit_res.summary())

Optimization terminated successfully.
         Current function value: 0.264930
         Iterations 6
                          Probit Regression Results
==============================================================================
Dep. Variable:                   call   No. Observations:                 4870
Model:                         Probit   Df Residuals:                     4845
Method:                           MLE   Df Model:                           24
Date:                Tue, 30 Jun 2026   Pseudo R-squ.:                 0.05372
Time:                        19:53:03   Log-Likelihood:                -1290.2
converged:                       True   LL-Null:                       -1363.5
Covariance Type:              cluster   LLR p-value:                 1.477e-19
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
white_dummy        0.2165      0.047      4.574      0.000       0.124       0.309
h                  0.1676      0.130      1.287      0.198      -0.088       0.423
const             -1.4717    1.4e+06  -1.05e-06      1.000   -2.74e+06    2.74e+06
yearsexp           0.0146      0.007      2.206      0.027       0.002       0.028
honors             0.2605      0.108      2.416      0.016       0.049       0.472
volunteer         -0.0960      0.091     -1.058      0.290      -0.274       0.082
military          -0.0450      0.099     -0.455      0.649      -0.239       0.149
email              0.0102      0.110      0.093      0.926      -0.206       0.226
empholes           0.1807      0.074      2.446      0.014       0.036       0.326
workinschool       0.0558      0.065      0.853      0.394      -0.072       0.184
computerskills    -0.1231      0.079     -1.563      0.118      -0.277       0.031
specialskills      0.3442      0.070      4.884      0.000       0.206       0.482
city_dummy        -0.1528      0.095     -1.604      0.109      -0.340       0.034
sex_dummy         -0.0254      0.081     -0.314      0.753      -0.183       0.133
manager           -0.3545   1.42e+06   -2.5e-07      1.000   -2.78e+06    2.78e+06
supervisor        -0.2715   1.38e+06  -1.97e-07      1.000    -2.7e+06     2.7e+06
secretary         -0.1941   1.57e+06  -1.24e-07      1.000   -3.08e+06    3.08e+06
offsupport        -0.1255   1.49e+06  -8.44e-08      1.000   -2.91e+06    2.91e+06
salesrep          -0.3061   1.54e+06  -1.98e-07      1.000   -3.02e+06    3.02e+06
retailsales       -0.2189    1.5e+06  -1.45e-07      1.000   -2.95e+06    2.95e+06
expreq             0.0212      0.082      0.258      0.796      -0.140       0.182
comreq             0.0892      0.125      0.715      0.474      -0.155       0.333
educreq           -0.1762      0.135     -1.304      0.192      -0.441       0.089
compreq           -0.1366      0.100     -1.366      0.172      -0.333       0.059
orgreq            -0.2549      0.193     -1.322      0.186      -0.633       0.123
==================================================================================

For info on marginal effects calcs see: https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.DiscreteResults.get_margeff.html

In [364]:
probit_me = probit_res.get_margeff(at = "overall",
                                  method = "dydx",
                                  dummy = [
                                      'white_dummy',
                                      'volunteer',
                                      'military',
                                      'email',
                                      'empholes',
                                      'workinschool',
                                      'computerskills',
                                      'specialskills',
                                      'city_dummy',
                                      'sex_dummy',
                                      'manager',
                                      'supervisor',
                                      'secretary',
                                      'offsupport',
                                      'salesrep',
                                      'retailsales',
                                      'expreq',
                                      'comreq',
                                      'educreq',
                                      'compreq',
                                      'orgreq'
                                  ])#at='overall', dummy=X[-20:])
print(probit_me.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:                   call
Method:                          dydx
At:                           overall
==================================================================================
                    dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
white_dummy        0.0306      0.006      4.797      0.000       0.018       0.043
h                  0.0238      0.018      1.312      0.190      -0.012       0.059
yearsexp           0.0021      0.001      2.075      0.038       0.000       0.004
honors             0.0429      0.020      2.103      0.035       0.003       0.083
volunteer         -0.0135      0.013     -1.054      0.292      -0.039       0.012
military          -0.0062      0.013     -0.466      0.641      -0.032       0.020
email              0.0014      0.016      0.092      0.926      -0.029       0.032
empholes           0.0259      0.010      2.633      0.008       0.007       0.045
workinschool       0.0079      0.009      0.880      0.379      -0.010       0.025
computerskills    -0.0184      0.011     -1.669      0.095      -0.040       0.003
specialskills      0.0523      0.011      4.652      0.000       0.030       0.074
city_dummy        -0.0219      0.014     -1.596      0.110      -0.049       0.005
sex_dummy         -0.0036      0.011     -0.317      0.751      -0.026       0.018
manager           -0.0429   1.39e+05  -3.08e-07      1.000   -2.72e+05    2.72e+05
supervisor        -0.0330   1.36e+05  -2.43e-07      1.000   -2.66e+05    2.66e+05
secretary         -0.0265   2.03e+05   -1.3e-07      1.000   -3.98e+05    3.98e+05
offsupport        -0.0167   1.84e+05  -9.11e-08      1.000    -3.6e+05     3.6e+05
salesrep          -0.0378    1.6e+05  -2.37e-07      1.000   -3.13e+05    3.13e+05
retailsales       -0.0283   1.74e+05  -1.63e-07      1.000    -3.4e+05     3.4e+05
expreq             0.0030      0.012      0.258      0.796      -0.020       0.026
comreq             0.0132      0.019      0.685      0.493      -0.025       0.051
educreq           -0.0227      0.016     -1.434      0.152      -0.054       0.008
compreq           -0.0191      0.014     -1.334      0.182      -0.047       0.009
orgreq            -0.0311      0.020     -1.558      0.119      -0.070       0.008
==================================================================================

If we consider that the baseline callback rate for job applications was ~ $8\%$ for all resumes; a 3% increase in the likelihood of recieving a callback simply for having a white sounding name actually equates to an ~ 38% relative increase in callback rate. The maths is below: 

$$ baseline \ Callbacks + Callbacks \ from \ White \ Name = 8\% + 3\% = 11\% $$ 

However, a 3% point increase relative to a 8% baseline callback rate equates to: 

$$ \frac{3/%}{8\%} = 38\% $$

That is, having a white name means you have a 38% higher

In [365]:
probit_me.margeff[0] / df[y].mean()

0.3800944700368759

In [366]:
info_dict={'Pseudo R2' : lambda x: f"{x.prsquared:.2f}",
           'No. observations' : lambda x: f"{int(x.nobs):d}"}

probit_results_table = summary_col(results=[sm.Probit(df[y], 
                                                      df[X]).fit(cov_type='cluster',  
                                                                 cov_kwds={'groups': df['adid']}), 
                                     sm.Probit(df.loc[df[T] == "w", y], 
                                               df.loc[df[T] == "w", 
                                                      X]).fit(cov_type='cluster',  
                                                              cov_kwds={'groups': df.loc[df['race'] == "w",
                                                                                         'adid']}), 
                                     sm.Probit(df.loc[df[T] == "b",y], 
                                               df.loc[df[T] == "b", X]).fit(cov_type='cluster',
                                                              cov_kwds={'groups': df.loc[df['race'] == "b",
                                                                                         'adid']})],
                            float_format='%0.3f',
                            stars = True,
                            model_names=['All resumes',
                                         'White names',
                                         ' African-American names'],
                            info_dict=info_dict)

probit_results_table.add_title('Probit coefficient comparison')

print(probit_results_table)

Optimization terminated successfully.
         Current function value: 0.266726
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.299603
         Iterations 6
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.228449
         Iterations: 35
                   Probit coefficient comparison
====================================================================
                  All resumes   White names   African-American names
--------------------------------------------------------------------
const            -1.373        -1.269        -1.495
                 (7221875.284) (727979.336)  (nan)
yearsexp         0.016**       0.016*        0.016*
                 (0.007)       (0.008)       (0.009)
honors           0.266**       0.286*        0.222
                 (0.108)       (0.151)       (0.159)
volunteer        -0.052        -0.126        0.054
                 (0.081)       (0.100)       (0.120)
military         -0.046        0.044         -0.146
                 (0.098)       (0.137)       (0.166)
email            0.130         0.221**       0.001
                 (0.079)       (0.101)       (0.115)
empholes         0.171**       0.217**       0.112
                 (0.076)       (0.099)       (0.110)
workinschool     0.064         0.111         -0.010
                 (0.065)       (0.088)       (0.103)
computerskills   -0.126        -0.214**      -0.009
                 (0.079)       (0.101)       (0.122)
specialskills    0.349***      0.358***      0.332***
                 (0.070)       (0.084)       (0.094)
city_dummy       -0.149        -0.177*       -0.116
                 (0.096)       (0.106)       (0.122)
sex_dummy        -0.019        -0.016        -0.041
                 (0.081)       (0.104)       (0.120)
manager          -0.325        -0.335        -0.332
                 (8238752.329) (1041702.323) (nan)
supervisor       -0.256        -0.167        -0.362
                 (nan)         (884484.551)  (nan)
secretary        -0.180        -0.122        -0.244
                 (3586667.351) (1250850.048) (nan)
offsupport       -0.114        -0.107        -0.114
                 (3851060.461) (1167363.969) (nan)
salesrep         -0.291        -0.304        -0.277
                 (8238912.461) (1329102.347) (nan)
retailsales      -0.205        -0.235        -0.167
                 (7996743.709) (1280755.068) (nan)
expreq           0.022         -0.012        0.064
                 (0.082)       (0.089)       (0.099)
comreq           0.091         0.111         0.073
                 (0.124)       (0.129)       (0.148)
educreq          -0.171        -0.072        -0.332*
                 (0.134)       (0.144)       (0.186)
compreq          -0.135        -0.167        -0.104
                 (0.099)       (0.110)       (0.121)
orgreq           -0.255        -0.350*       -0.148
                 (0.191)       (0.189)       (0.236)
Pseudo R2        0.05          0.06          0.04
No. observations 4870          2435          2435
====================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

/usr/lib/python3/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [367]:
probit_me_all = sm.Probit(df[y],
          df[X]).fit(cov_type='cluster', 
                     cov_kwds={'groups': df['adid']}).get_margeff() 

all_probit_coef = probit_me_all.margeff
all_probit_p  = probit_me_all.pvalues

probit_me_white = sm.Probit(df.loc[df[T] == "w", y], 
          df.loc[df[T] == "w", 
                 X]).fit(cov_type='cluster',
                         cov_kwds={'groups': df.loc[df['race'] == "w",
                                                    'adid']}).get_margeff()

white_probit_coef = probit_me_white.margeff
white_probit_p  = probit_me_white.pvalues

probit_me_black = sm.Probit(df.loc[df[T] == "b",y],
          df.loc[df[T] == "b", X]).fit(cov_type='cluster',
                                       cov_kwds={'groups': df.loc[df['race'] == "b",
                                                                  'adid']}).get_margeff()


black_probit_coef = probit_me_black.margeff
black_probit_p  = probit_me_black.pvalues

# join into one DataFrame
df1 = pd.concat([pd.DataFrame({'vari':X}), 
                 pd.DataFrame({'Probit ME - All': all_probit_coef.round(4)}),
                 pd.DataFrame({'Probit p-val - All': all_probit_p.round(2)}),
                 pd.DataFrame({'Probit ME - white': white_probit_coef.round(4)}),
                 pd.DataFrame({'Probit p-val - white': white_probit_p.round(2)}),
                 pd.DataFrame({'Probit ME - African-American': black_probit_coef.round(4)}),
                 pd.DataFrame({'Probit p-val - African-American': black_probit_p.round(2)}),],
                axis=1, 
                join='inner')

df1

Optimization terminated successfully.
         Current function value: 0.266726
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.299603
         Iterations 6

/usr/lib/python3/dist-packages/statsmodels/discrete/discrete_margins.py:343: RuntimeWarning: invalid value encountered in sqrt
  return cov_me, np.sqrt(np.diag(cov_me))

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.228449
         Iterations: 35

/usr/lib/python3/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/lib/python3/dist-packages/statsmodels/discrete/discrete_margins.py:343: RuntimeWarning: invalid value encountered in sqrt
  return cov_me, np.sqrt(np.diag(cov_me))

,vari,Probit ME - All,Probit p-val - All,Probit ME - white,Probit p-val - white,Probit ME - African-American,Probit p-val - African-American
0,const,0.0022,0.08,0.0026,0.09,0.0019,NaN
1,yearsexp,0.0380,NaN,0.0463,0.05,0.0269,NaN
2,honors,-0.0075,0.58,-0.0204,0.22,0.0065,NaN
3,volunteer,-0.0065,0.66,0.0072,0.75,-0.0177,0.60
4,military,0.0185,0.43,0.0357,0.04,0.0001,0.99
5,email,0.0244,0.34,0.0351,0.03,0.0136,0.74
6,empholes,0.0091,0.27,0.0180,0.21,-0.0013,0.80
7,workinschool,-0.0180,0.03,-0.0347,0.03,-0.0011,0.91
8,computerskills,0.0498,0.03,0.0579,0.00,0.0401,NaN
9,specialskills,-0.0213,0.00,-0.0286,0.10,-0.0140,NaN
10,city_dummy,-0.0027,0.83,-0.0026,0.88,-0.0049,NaN
11,sex_dummy,-0.0464,1.00,-0.0541,1.00,-0.0401,NaN
12,manager,-0.0365,NaN,-0.0270,1.00,-0.0438,NaN
13,supervisor,-0.0257,1.00,-0.0197,1.00,-0.0295,NaN
14,secretary,-0.0163,1.00,-0.0173,1.00,-0.0138,NaN
15,offsupport,-0.0415,1.00,-0.0491,1.00,-0.0335,NaN
16,salesrep,-0.0292,1.00,-0.0381,1.00,-0.0202,NaN
17,retailsales,0.0031,0.76,-0.0020,0.89,0.0077,NaN
18,expreq,0.0130,0.43,0.0180,0.39,0.0088,0.47
19,comreq,-0.0244,0.13,-0.0116,0.62,-0.0402,NaN
20,educreq,-0.0192,0.21,-0.0270,0.13,-0.0125,NaN
21,compreq,-0.0364,0.27,-0.0566,0.06,-0.0179,0.60

# Logit coefficients and Marginal effect table

In [368]:
logit_res = sm.Logit(df[y], df[["white_dummy", "h"] + X]).fit(cov_type='cluster', 
                                         cov_kwds={'groups': df['adid']})
print(logit_res.summary())

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.264801
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                   call   No. Observations:                 4870
Model:                          Logit   Df Residuals:                     4845
Method:                           MLE   Df Model:                           24
Date:                Tue, 30 Jun 2026   Pseudo R-squ.:                 0.05418
Time:                        19:53:03   Log-Likelihood:                -1289.6
converged:                      False   LL-Null:                       -1363.5
Covariance Type:              cluster   LLR p-value:                 8.645e-20
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
white_dummy        0.4447      0.220      2.025      0.043       0.014       0.875
h                  0.3429      0.278      1.234      0.217      -0.202       0.888
const             -2.6243    9.2e+06  -2.85e-07      1.000    -1.8e+07     1.8e+07
yearsexp           0.0269      0.013      2.098      0.036       0.002       0.052
honors             0.4708      0.207      2.274      0.023       0.065       0.876
volunteer         -0.1826      0.179     -1.020      0.308      -0.534       0.168
military          -0.1001      0.203     -0.492      0.622      -0.499       0.298
email              0.0243      0.222      0.109      0.913      -0.411       0.459
empholes           0.3612      0.153      2.353      0.019       0.060       0.662
workinschool       0.0948      0.133      0.711      0.477      -0.167       0.356
computerskills    -0.2705      0.157     -1.720      0.085      -0.579       0.038
specialskills      0.6911      0.145      4.765      0.000       0.407       0.975
city_dummy        -0.3029      0.193     -1.572      0.116      -0.681       0.075
sex_dummy         -0.0412      0.167     -0.247      0.805      -0.368       0.286
manager           -0.6779    8.9e+06  -7.61e-08      1.000   -1.75e+07    1.75e+07
supervisor        -0.4793   9.67e+06  -4.95e-08      1.000    -1.9e+07     1.9e+07
secretary         -0.3434   9.81e+06   -3.5e-08      1.000   -1.92e+07    1.92e+07
offsupport        -0.1938   9.13e+06  -2.12e-08      1.000   -1.79e+07    1.79e+07
salesrep          -0.5468   8.71e+06  -6.28e-08      1.000   -1.71e+07    1.71e+07
retailsales       -0.3829   9.92e+06  -3.86e-08      1.000   -1.94e+07    1.94e+07
expreq             0.0463      0.169      0.274      0.784      -0.285       0.377
comreq             0.2099      0.251      0.837      0.403      -0.282       0.702
educreq           -0.3451      0.287     -1.202      0.229      -0.908       0.218
compreq           -0.2799      0.198     -1.411      0.158      -0.669       0.109
orgreq            -0.5355      0.416     -1.286      0.198      -1.352       0.281
==================================================================================

/usr/lib/python3/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [369]:
logit_me = logit_res.get_margeff()
print(logit_me.summary())

        Logit Marginal Effects
=====================================
Dep. Variable:                   call
Method:                          dydx
At:                           overall
==================================================================================
                    dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
white_dummy        0.0317      0.016      1.976      0.048       0.000       0.063
h                  0.0245      0.020      1.205      0.228      -0.015       0.064
yearsexp           0.0019      0.001      3.257      0.001       0.001       0.003
honors             0.0336      0.015      2.217      0.027       0.004       0.063
volunteer         -0.0130      0.012     -1.114      0.265      -0.036       0.010
military          -0.0071      0.015     -0.491      0.624      -0.036       0.021
email              0.0017      0.016      0.110      0.913      -0.029       0.033
empholes           0.0258      0.010      2.550      0.011       0.006       0.046
workinschool       0.0068      0.009      0.740      0.460      -0.011       0.025
computerskills    -0.0193      0.015     -1.266      0.206      -0.049       0.011
specialskills      0.0493        nan        nan        nan         nan         nan
city_dummy        -0.0216      0.014     -1.576      0.115      -0.049       0.005
sex_dummy         -0.0029      0.012     -0.244      0.807      -0.027       0.021
manager           -0.0484   6.26e+05  -7.74e-08      1.000   -1.23e+06    1.23e+06
supervisor        -0.0342   6.84e+05     -5e-08      1.000   -1.34e+06    1.34e+06
secretary         -0.0245   6.96e+05  -3.52e-08      1.000   -1.36e+06    1.36e+06
offsupport        -0.0138   6.49e+05  -2.13e-08      1.000   -1.27e+06    1.27e+06
salesrep          -0.0390   6.14e+05  -6.36e-08      1.000    -1.2e+06     1.2e+06
retailsales       -0.0273   7.03e+05  -3.89e-08      1.000   -1.38e+06    1.38e+06
expreq             0.0033      0.012      0.276      0.783      -0.020       0.027
comreq             0.0150      0.018      0.844      0.399      -0.020       0.050
educreq           -0.0246      0.020     -1.245      0.213      -0.063       0.014
compreq           -0.0200      0.014     -1.399      0.162      -0.048       0.008
orgreq            -0.0382      0.030     -1.294      0.196      -0.096       0.020
==================================================================================

/usr/lib/python3/dist-packages/statsmodels/discrete/discrete_margins.py:343: RuntimeWarning: invalid value encountered in sqrt
  return cov_me, np.sqrt(np.diag(cov_me))

In [370]:
info_dict={'Pseudo R2' : lambda x: f"{x.prsquared:.2f}",
           'No. observations' : lambda x: f"{int(x.nobs):d}"}

probit_results_table = summary_col(results=[sm.Logit(df[y], 
                                                      df[X]).fit(cov_type='cluster',  
                                                                 cov_kwds={'groups': df['adid']}), 
                                     sm.Logit(df.loc[df[T] == "w", y], 
                                               df.loc[df[T] == "w", 
                                                      X]).fit(cov_type='cluster',  
                                                              cov_kwds={'groups': df.loc[df['race'] == "w",
                                                                                         'adid']}), 
                                     sm.Logit(df.loc[df[T] == "b",y], 
                                               df.loc[df[T] == "b", X]).fit(cov_type='cluster',
                                                              cov_kwds={'groups': df.loc[df['race'] == "b",
                                                                                         'adid']})],
                            float_format='%0.3f',
                            stars = True,
                            model_names=['All resumes',
                                         'White names',
                                         'African-American names'],
                            info_dict=info_dict)

probit_results_table.add_title('Logit coefficient comparison')

print(probit_results_table)

Optimization terminated successfully.
         Current function value: 0.266693
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.299647
         Iterations 7
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.228170
         Iterations: 35

/usr/lib/python3/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

                  Logit coefficient comparison
=================================================================
                 All resumes  White names  African-American names
-----------------------------------------------------------------
const            -2.416      -2.186        -2.713
                 (nan)       (nan)         (nan)
yearsexp         0.028**     0.027*        0.032*
                 (0.013)     (0.016)       (0.019)
honors           0.479**     0.483*        0.439
                 (0.207)     (0.287)       (0.308)
volunteer        -0.091      -0.240        0.131
                 (0.158)     (0.195)       (0.245)
military         -0.103      0.084         -0.345
                 (0.202)     (0.272)       (0.362)
email            0.259*      0.439**       -0.005
                 (0.155)     (0.200)       (0.225)
empholes         0.339**     0.412**       0.235
                 (0.156)     (0.204)       (0.237)
workinschool     0.112       0.199         -0.033
                 (0.132)     (0.172)       (0.216)
computerskills   -0.271*     -0.431**      -0.031
                 (0.156)     (0.192)       (0.241)
specialskills    0.701***    0.694***      0.700***
                 (0.144)     (0.169)       (0.196)
city_dummy       -0.292      -0.355*       -0.214
                 (0.190)     (0.207)       (0.241)
sex_dummy        -0.027      -0.017        -0.057
                 (0.163)     (0.202)       (0.245)
manager          -0.612      -0.613        -0.652
                 (nan)       (nan)         (nan)
supervisor       -0.451      -0.273        -0.670
                 (nan)       (nan)         (nan)
secretary        -0.317      -0.203        -0.441
                 (nan)       (702497.016)  (1147732.130)
offsupport       -0.169      -0.160        -0.157
                 (nan)       (1041971.462) (nan)
salesrep         -0.515      -0.546        -0.484
                 (nan)       (1720759.236) (nan)
retailsales      -0.352      -0.390        -0.310
                 (nan)       (nan)         (nan)
expreq           0.049       -0.038        0.156
                 (0.168)     (0.177)       (0.212)
comreq           0.214       0.252         0.168
                 (0.251)     (0.253)       (0.316)
educreq          -0.342      -0.108        -0.761*
                 (0.286)     (0.297)       (0.431)
compreq          -0.276      -0.324        -0.233
                 (0.197)     (0.213)       (0.252)
orgreq           -0.531      -0.715*       -0.304
                 (0.415)     (0.406)       (0.520)
Pseudo R2        0.05        0.06          0.05
No. observations 4870        2435          2435
=================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01