In [1]:
%reset -f

# load all packages

In [1]:
import matplotlib.pyplot as plt
import numpy             as np
import pandas            as pd
import statsmodels.api   as sm

# load data into Python

In [13]:
df = pd.read_csv("https://raw.githubusercontent.com/Michael-Morgan-Giles/python-causality-handbook/refs/heads/master/causal-inference-for-the-brave-and-true/data/smoking.csv")

# check the head of your table

In [3]:
df.head()

,state,year,cigsale,lnincome,beer,age15to24,retprice,california,after_treatment
0,1,1970,89.800003,NaN,NaN,0.178862,39.599998,False,False
1,1,1971,95.400002,NaN,NaN,0.179928,42.700001,False,False
2,1,1972,101.099998,9.498476,NaN,0.180994,42.299999,False,False
3,1,1973,102.900002,9.550107,NaN,0.182060,42.099998,False,False
4,1,1974,108.199997,9.537163,NaN,0.183126,43.099998,False,False

In [14]:
df.shape

(1209, 9)

# add constant term

In [19]:
df = sm.add_constant(df)

/usr/lib/python3/dist-packages/numpy/core/_methods.py:41: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
/usr/lib/python3/dist-packages/numpy/core/_methods.py:45: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial, where)

create necessary variables

In [17]:
df['treated'] = np.where(df['california'] == True,1,0)
df['post_treat'] = np.where(df['after_treatment'] == True,1,0)
df['int_for_now'] = df['treated']*df['post_treat']
df = pd.concat([df,pd.get_dummies(df['year']).astype(float)])

# check the summary statistics

In [16]:
df.describe()

,state,year,cigsale,lnincome,beer,age15to24,retprice,treated,post_treat,1970,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
count,1209.000000,1209.000000,1209.000000,1014.000000,546.000000,819.000000,1209.000000,1209.000000,1209.000000,1209.000000,...,1209.000000,1209.000000,1209.000000,1209.000000,1209.000000,1209.000000,1209.000000,1209.000000,1209.000000,1209.000000
mean,20.000000,1985.000000,118.893218,9.861634,23.430403,0.175472,108.341936,0.025641,0.387097,0.032258,...,0.032258,0.032258,0.032258,0.032258,0.032258,0.032258,0.032258,0.032258,0.032258,0.032258
std,11.259286,8.947973,32.767404,0.170677,4.223190,0.015159,64.381986,0.158127,0.487288,0.176758,...,0.176758,0.176758,0.176758,0.176758,0.176758,0.176758,0.176758,0.176758,0.176758,0.176758
min,1.000000,1970.000000,40.700001,9.397449,2.500000,0.129448,27.299999,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,1977.000000,100.900002,9.739134,20.900000,0.165816,50.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,20.000000,1985.000000,116.300003,9.860844,23.299999,0.178121,95.500000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,30.000000,1993.000000,130.500000,9.972764,25.100000,0.186660,158.399994,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,39.000000,2000.000000,296.200012,10.486617,40.400002,0.203675,351.200012,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# check variable names

In [7]:
df.columns

Index(['const', 'year', 'age', 'agesq', 'nbh', 'cbd', 'intst', 'lintst',
       'price', 'rooms', 'area', 'land', 'baths', 'dist', 'ldist', 'wind',
       'lprice', 'y81', 'larea', 'lland', 'y81ldist', 'lintstsq', 'nearinc',
       'y81nrinc', 'rprice', 'lrprice'],
      dtype='object')

# (c)

In [28]:
print(sm.OLS(df[['cigsale']], 
            df[['const',
                'treated',
                'post_treat',
                'int_for_now']], 
           missing = "drop").fit(cov_type = "HC3").summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                cigsale   R-squared:                       0.207
Model:                            OLS   Adj. R-squared:                  0.205
Method:                 Least Squares   F-statistic:                     172.0
Date:                Tue, 16 Jun 2026   Prob (F-statistic):           8.16e-93
Time:                        19:54:41   Log-Likelihood:                -5793.3
No. Observations:                1209   AIC:                         1.159e+04
Df Residuals:                    1205   BIC:                         1.161e+04
Df Model:                           3
Covariance Type:                  HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const         130.5695      1.218    107.224      0.000     128.183     132.956
treated       -14.3590      3.011     -4.769      0.000     -20.260      -8.458
post_treat    -28.5114      1.645    -17.333      0.000     -31.735     -25.287
int_for_now   -27.3491      4.854     -5.634      0.000     -36.863     -17.836
==============================================================================
Omnibus:                      470.050   Durbin-Watson:                   0.130
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2334.004
Skew:                           1.760   Prob(JB):                         0.00
Kurtosis:                       8.826   Cond. No.                         15.4
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)