In [1]:
%reset -f

# load all packages

In [1]:
import matplotlib.pyplot as plt
import numpy             as np
import pandas            as pd
import statsmodels.api   as sm

# load data into Python

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/Michael-Morgan-Giles/python-causality-handbook/refs/heads/master/causal-inference-for-the-brave-and-true/data/smoking.csv")

# check the head of your table

In [3]:
df.head()

,state,year,cigsale,lnincome,beer,age15to24,retprice,california,after_treatment
0,1,1970,89.800003,NaN,NaN,0.178862,39.599998,False,False
1,1,1971,95.400002,NaN,NaN,0.179928,42.700001,False,False
2,1,1972,101.099998,9.498476,NaN,0.180994,42.299999,False,False
3,1,1973,102.900002,9.550107,NaN,0.182060,42.099998,False,False
4,1,1974,108.199997,9.537163,NaN,0.183126,43.099998,False,False

In [4]:
df.shape

(1209, 9)

# add constant term

In [5]:
df = sm.add_constant(df)

# check the summary statistics

In [6]:
df.describe()

,const,year,age,agesq,nbh,cbd,intst,lintst,price,rooms,...,lprice,y81,larea,lland,y81ldist,lintstsq,nearinc,y81nrinc,rprice,lrprice
count,321.0,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,...,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000
mean,1.0,1979.327103,18.009346,1381.566978,2.208723,15822.429907,16442.367601,9.480513,96100.660436,6.585670,...,11.378118,0.442368,7.597232,10.301859,4.342579,90.482240,0.299065,0.124611,83721.355097,11.261376
std,0.0,1.492329,32.565845,4801.788757,2.164353,8967.106296,9033.130652,0.777165,43223.728867,0.901204,...,0.438174,0.497443,0.340723,0.801752,4.892513,14.066464,0.458563,0.330792,33118.785377,0.387900
min,1.0,1978.000000,0.000000,0.000000,0.000000,1000.000000,1000.000000,6.907800,26000.000000,4.000000,...,10.165852,0.000000,6.599871,7.444249,0.000000,47.717705,0.000000,0.000000,26000.000000,10.165852
25%,1.0,1978.000000,0.000000,0.000000,0.000000,9000.000000,9000.000000,9.104999,65000.000000,6.000000,...,11.082143,0.000000,7.352441,9.737138,0.000000,82.901016,0.000000,0.000000,59000.000000,10.985292
50%,1.0,1978.000000,4.000000,16.000000,2.000000,14000.000000,16000.000000,9.680300,85900.000000,7.000000,...,11.360939,0.000000,7.628518,10.681894,0.000000,93.708206,0.000000,0.000000,82000.000000,11.314474
75%,1.0,1981.000000,22.000000,484.000000,4.000000,23000.000000,24000.000000,10.086000,120000.000000,7.000000,...,11.695247,1.000000,7.841493,10.738568,9.820106,101.727400,1.000000,0.000000,100230.410000,11.515227
max,1.0,1981.000000,189.000000,35721.000000,6.000000,35000.000000,34000.000000,10.434000,300000.000000,10.000000,...,12.611538,1.000000,8.544030,13.207623,10.568750,108.868350,1.000000,1.000000,300000.000000,12.611538

# check variable names

In [7]:
df.columns

Index(['const', 'year', 'age', 'agesq', 'nbh', 'cbd', 'intst', 'lintst',
       'price', 'rooms', 'area', 'land', 'baths', 'dist', 'ldist', 'wind',
       'lprice', 'y81', 'larea', 'lland', 'y81ldist', 'lintstsq', 'nearinc',
       'y81nrinc', 'rprice', 'lrprice'],
      dtype='object')

# (c)

In [8]:
X_1   = df[['const', 'y81', 'nearinc', 'y81nrinc']]
Y_1   = df[['lrprice']]
M1 = sm.OLS(Y_1, X_1, missing='drop')

OLS1 = M1.fit()
print(OLS1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                lrprice   R-squared:                       0.246
Model:                            OLS   Adj. R-squared:                  0.239
Method:                 Least Squares   F-statistic:                     34.47
Date:                Mon, 10 May 2021   Prob (F-statistic):           2.62e-19
Time:                        01:34:52   Log-Likelihood:                -105.68
No. Observations:                 321   AIC:                             219.4
Df Residuals:                     317   BIC:                             234.4
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         11.2854      0.031    369.839      0.000      11.225      11.345
y81            0.1931      0.045      4.261      0.000       0.104       0.282
nearinc       -0.3399      0.055     -6.231      0.000      -0.447      -0.233
y81nrinc      -0.0626      0.083     -0.751      0.453      -0.227       0.102
==============================================================================
Omnibus:                       29.462   Durbin-Watson:                   1.568
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               84.380
Skew:                           0.370   Prob(JB):                     4.75e-19
Kurtosis:                       5.400   Cond. No.                         6.05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# (e)

In [9]:
X_2 = df[['const', 'y81', 'ldist', 'y81ldist']]
Y_2 = df[['lprice']]
M2  = sm.OLS(Y_2, X_2, missing='drop')

OLS2 = M2.fit()
print(OLS2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 lprice   R-squared:                       0.396
Model:                            OLS   Adj. R-squared:                  0.390
Method:                 Least Squares   F-statistic:                     69.22
Date:                Mon, 10 May 2021   Prob (F-statistic):           1.87e-34
Time:                        01:34:52   Log-Likelihood:                -109.24
No. Observations:                 321   AIC:                             226.5
Df Residuals:                     317   BIC:                             241.6
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          8.0585      0.508     15.850      0.000       7.058       9.059
y81           -0.0113      0.805     -0.014      0.989      -1.595       1.573
ldist          0.3167      0.052      6.145      0.000       0.215       0.418
y81ldist       0.0482      0.082      0.589      0.556      -0.113       0.209
==============================================================================
Omnibus:                       10.892   Durbin-Watson:                   1.395
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               16.703
Skew:                           0.224   Prob(JB):                     0.000236
Kurtosis:                       4.024   Cond. No.                         512.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# (f)

In [10]:
X_3 = df[['const', 'y81', 'ldist', 'y81ldist', 'age', 'agesq',
          'rooms', 'baths', 'lintst', 'lland', 'larea']]
Y_3 = df[['lprice']]
M3  = sm.OLS(Y_3, X_3, missing='drop')

OLS3 = M3.fit()
print(OLS3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 lprice   R-squared:                       0.787
Model:                            OLS   Adj. R-squared:                  0.780
Method:                 Least Squares   F-statistic:                     114.6
Date:                Mon, 10 May 2021   Prob (F-statistic):           7.73e-98
Time:                        01:34:52   Log-Likelihood:                 58.114
No. Observations:                 321   AIC:                            -94.23
Df Residuals:                     310   BIC:                            -52.74
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.6739      0.502     15.300      0.000       6.687       8.661
y81           -0.2254      0.495     -0.456      0.649      -1.199       0.748
ldist          0.0009      0.045      0.021      0.984      -0.087       0.089
y81ldist       0.0625      0.050      1.242      0.215      -0.036       0.161
age           -0.0080      0.001     -5.650      0.000      -0.011      -0.005
agesq        3.57e-05   8.71e-06      4.099      0.000    1.86e-05    5.28e-05
rooms          0.0461      0.017      2.660      0.008       0.012       0.080
baths          0.1010      0.028      3.632      0.000       0.046       0.156
lintst        -0.0600      0.032     -1.891      0.060      -0.122       0.002
lland          0.0953      0.025      3.856      0.000       0.047       0.144
larea          0.3507      0.052      6.752      0.000       0.249       0.453
==============================================================================
Omnibus:                       66.092   Durbin-Watson:                   1.691
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              350.050
Skew:                          -0.716   Prob(JB):                     9.72e-77
Kurtosis:                       7.912   Cond. No.                     2.61e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.61e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [1]:
!rm -rf W8_Python.html
!jupyter nbconvert --to html W8_Python.ipynb

[NbConvertApp] Converting notebook W8_Python.ipynb to html
[NbConvertApp] Writing 604117 bytes to W8_Python.html